name: dbt_test_run

on:
  push:
      branches:
      # run on push to development branch
      #- development
env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_BIGQUERY_KEYFILE: credentials/bigquery_service_account.json 

jobs:
  run_dbt_tests:
      name: run_dbt_tests
      runs-on: ubuntu-latest

      steps:
        - name: Check out
          uses: actions/checkout@master

        - uses: actions/setup-python@v3
          with:
            python-version: "3.8"

        - name: Install dependencies
          run: |
            pip install dbt-bigquery
            dbt --no-version-check deps
     
        - name: Generate BigQuery service account credentials
          working-directory: ./
    
          run: 'echo "$KEYFILE" > credentials/bigquery_service_account.json'
          shell: bash
          env:
             KEYFILE: ${{ secrets.DBT_GOOGLE_BIGQUERY_KEYFILE }}

        - name: Debug dbt models
          run: dbt debug --no-version-check --profiles-dir ./

        - name: Run dbt models
          run: dbt run --no-version-check --profiles-dir ./

        - name: Test dbt models
          run: dbt test --no-version-check --profiles-dir ./
          
       